### ISSUE TITLE
z-index issues ?

### ISSUE THREAD

**Issue by karloxe** [adorsk/jquery.window#1]
Hi, can someone help a bit on this ?
I tried several times to solve it but with no luck,
 also tried to contact the original creator , but I can't find his email ( please send me a PM in case you know)
The 2 issues are :
1 - overlapping 3 windows and activating one at a time does not maintain the correct order ( in the 2 behind) the one clicked before actual goes to bottom.
2.- I can't place any window in front of a maximized one
Thanks in advance

**Comment by adorsk** [comment]
Hi @karloxe, unfortunately I don't have the contact info for the original info, and I can't help out with this at the moment.

However, feel free to fork this repo.

I also suspect that there are now better windowing solutions than this code (which is 4+ years old!). So I recommend finding something else before putting a lot of time into this.
